version: '3'

services:

  mysqldb:
    image: mysql
    networks:
      - springboot-db-net
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  application:
    image: spring-boot-mysql-app
    ports:
      - "8080:8080"
    expose:
      - 8080
    networks:
      - springboot-db-net
    depends_on:
      - mysqldb
    volumes:
      - /data/springboot-app

networks:
  springboot-db-net:
