version: '3'

services:

  mysqldb:
    image: mysql
    networks:
      - gse-cart-net
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gse_cart
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./src/main/resources/schema.sql://docker-entrypoint-initdb.d/schema.sql

  application:
    image: faisalhn/gse-cart-contact-app
    ports:
      - "8080:8080"
    expose:
      - 8080
    networks:
      - gse-cart-net
    depends_on:
      - mysqldb
    volumes:
      - /data/springboot-app

networks:
  gse-cart-net:
